blog/api/v1/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from blog.api.v1 import api
from blog.api.v1.viewset import ArticleViewSet

router = DefaultRouter()
router.register("article", ArticleViewSet)

urlpatterns = [
    path("", include(router.urls)),
    path("article-approval/", api.ArticleApproval.as_view(), name="ArticleApproval"),
    path("articles-edited/", api.ArticleEdited.as_view(), name="ArticleEdited"),
]

blog/urls.py
from django.urls import path

from blog.views import ArticleView, ArticleDetailView, ArticleApprove, ArticleEdited

urlpatterns = [
    path("article/", ArticleView.as_view(), name="article_listing"),
    path(
        "article/<int:article_id>/", ArticleDetailView.as_view(), name="article_detail"
    ),
    path("article-approval/", ArticleApprove.as_view(), name="article_approve"),
    path("articles-edited/", ArticleEdited.as_view(), name="article_edited"),
]

blogProject/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import dashboardView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("api/v1/", include(("blog.api.v1.urls", "blog"), namespace="blog-api-v1")),
    path("dashboard/", dashboardView.as_view(), name="dashboard_index"),
    path("", include(("blog.urls", "blog"), namespace="blog")),
]

blog/models.py
from django.db import models

# Create your models here.
from blogProject.constants import ARTICLE_STATUS, ArticleStatus


class Article(models.Model):
    title = models.CharField(
        max_length=128,
    )
    content = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=ARTICLE_STATUS, default=ArticleStatus.DRAFT)
    written_by = models.ForeignKey(
        "users.Writer",
        on_delete=models.SET_NULL,
        null=True,
        related_name="writer_articles",
    )
    edited_by = models.ForeignKey(
        "users.Writer",
        on_delete=models.SET_NULL,
        null=True,
        related_name="editor_articles",
    )

blog/forms.py
from django import forms
from django.core.exceptions import ValidationError

from blog.models import Article


class CreateArticleForm(forms.Form):
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea())

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        content = cleaned_data.get("content")
        if Article.objects.filter(title=title).count() > 0:
            raise ValidationError({"title": "This title already exists!"})


class UpdateArticleForm(forms.Form):
    id = forms.IntegerField(required=False)
    title = forms.CharField()
    content = forms.CharField(widget=forms.Textarea())

    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")
        content = cleaned_data.get("content")
        id = cleaned_data.get("id")
        if id and Article.objects.filter(title=title).exclude(id=id).count() > 0:
            raise ValidationError({"title": "This title already exists!"})

blog/views.py
from datetime import timedelta, datetime

from django.contrib.auth.decorators import login_required
from django.db.models import Count, Q
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.views.generic import TemplateView

from blog.forms import CreateArticleForm, UpdateArticleForm
from blog.models import Article
from blogProject.constants import ArticleStatus
from users.models import Writer


class dashboardView(TemplateView):
    template_name = "dashboard/index.html"

    def get(self, request, *args, **kwargs):
        last_30_days = datetime.today() - timedelta(days=30)
        articles_thirty = Count(
            "writer_articles", filter=Q(writer_articles__created_at__gte=last_30_days)
        )
        articles_total = Count("writer_articles")
        writers = (
            Writer.objects.all()
            .annotate(articles_total=articles_total)
            .annotate(articles_thirty=articles_thirty)
        )
        context = {"writers": writers}
        return render(request, self.template_name, context)


class ArticleView(TemplateView):
    template_name = "blog/article_list.html"

    def get(self, request, *args, **kwargs):
        articles = Article.objects.all()
        form = CreateArticleForm()
        context = {"articles": articles, "form": form}
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="/admin/login"))
    def post(self, request, *args, **kwargs):
        try:
            writer = request.user.writer_user
        except:
            return render(
                request,
                self.template_name,
                {"error": "Login with a user who is writer"},
            )
        form = CreateArticleForm(request.POST)
        success = False
        if form.is_valid():
            Article.objects.create(
                title=form.cleaned_data["title"],
                content=form.cleaned_data["content"],
                written_by=writer,
            )
            success = True
        articles = Article.objects.all()
        context = {"form": form, "articles": articles, "success": success}
        return render(request, self.template_name, context)


class ArticleDetailView(TemplateView):
    template_name = "blog/article_details.html"

    @method_decorator(login_required(login_url="/admin/login"))
    def get(self, request, *args, **kwargs):
        try:
            writer = request.user.writer_user
        except:
            return render(
                request,
                self.template_name,
                {"error": "Login with a user who is writer"},
            )
        try:
            article_id = kwargs["article_id"]
            article = Article.objects.get(id=article_id)
        except KeyError:
            return 404
        except Article.DoesNotExist:
            return 404
        except Article.MultipleObjectsReturned:
            return 404

        form = UpdateArticleForm(
            data={"title": article.title, "content": article.content}
        )
        context = {"article": article, "form": form, "is_editor": writer.is_editor}
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="/admin/login"))
    def post(self, request, *args, **kwargs):
        try:
            writer = request.user.writer_user
        except:
            return render(
                request,
                self.template_name,
                {"error": "Login with a user who is writer"},
            )
        article_id = kwargs["article_id"]
        data = request.POST.copy()
        data.update({"id": article_id})
        form = UpdateArticleForm(data)
        success = False
        if form.is_valid():
            Article.objects.filter(id=article_id).update(
                title=form.cleaned_data["title"],
                content=form.cleaned_data["content"],
                status=ArticleStatus.DRAFT,
            )
            success = True
        articles = Article.objects.all()
        context = {
            "form": form,
            "articles": articles,
            "is_editor": writer.is_editor,
            "success": success,
        }
        return render(request, self.template_name, context)


class ArticleApprove(TemplateView):
    template_name = "blog/article_approve.html"

    @method_decorator(login_required(login_url="/admin/login"))
    def get(self, request, *args, **kwargs):
        try:
            writer = request.user.writer_user
            if not writer.is_editor:
                return render(
                    request,
                    self.template_name,
                    {"error": "Login with a user who is editor"},
                )
        except:
            return render(
                request,
                self.template_name,
                {"error": "Login with a user who is writer"},
            )
        articles = Article.objects.filter(status=ArticleStatus.DRAFT)
        context = {"articles": articles}
        return render(request, self.template_name, context)

    @method_decorator(login_required(login_url="/admin/login"))
    def post(self, request, *args, **kwargs):
        try:
            writer = request.user.writer_user
            if not writer.is_editor:
                return render(
                    request,
                    self.template_name,
                    {"error": "Login with a user who is editor"},
                )
        except:
            return render(
                request,
                self.template_name,
                {"error": "Login with a user who is writer"},
            )

        action = request.POST.get("action", None)
        article_id = request.POST.get("article_id", None)
        if action and article_id:
            if action == "approve":
                status = ArticleStatus.PUBLISHED
            elif action == "reject":
                status = ArticleStatus.REJECTED
            else:
                status = ArticleStatus.DRAFT
            article = Article.objects.filter(id=article_id).update(
                edited_by=writer, status=status
            )
        articles = Article.objects.filter(status=ArticleStatus.DRAFT)
        context = {"articles": articles}
        return render(request, self.template_name, context)


class ArticleEdited(TemplateView):
    template_name = "blog/article_edited.html"

    def get(self, request, *args, **kwargs):
        try:
            writer = request.user.writer_user
            if not writer.is_editor:
                return render(
                    request,
                    self.template_name,
                    {"error": "Login with a user who is editor"},
                )
        except:
            return render(
                request,
                self.template_name,
                {"error": "Login with a user who is writer"},
            )
        articles = Article.objects.filter(edited_by=writer)
        context = {"articles": articles}
        return render(request, self.template_name, context)

templates/blog/article_approve.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <h2>USER: {{ request.user }}</h2>
    {% if error %}
        {{ error }}
    {% else %}
        <div class="text-center"><h3>Articles List</h3></div>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>Title</th>
                    <th>Written By</th>
                    <th>created at</th>
                    <th colspan="2" class="text-center">Action</th>
                </tr>
                </thead>
                <tbody>
                {% if articles %}
                    {% for article in articles %}
                        <tr>
                            <td scope="row"><a href="{% url "blog:article_detail" article.id %}">{{ article.title }}</a>
                            </td>
                            <td>{{ article.written_by.user.name }}</td>
                            <td>{{ article.created_at }}</td>
                            <td>
                                <form action="#" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="approve" name="action">
                                    <input type="hidden" value="{{ article.id }}" name="article_id">
                                    <button class="btn btn-link">Approve</button>
                                </form>
                            </td>
                            <td>
                                <form action="#" method="post">
                                    {% csrf_token %}
                                    <input type="hidden" value="reject" name="action">
                                    <input type="hidden" value="{{ article.id }}" name="article_id">
                                    <button class="btn btn-link">Reject</button>
                                </form>
                            </td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <tr>
                        <td colspan="5" class="text-center ">No Data</td>
                    </tr>
                {% endif %}

                </tbody>
            </table>
        </div>
    {% endif %}

{% endblock %}

templates/blog/article_details.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <h2>USER: {{ request.user }}</h2>
    <div class=''>
        <h3>Update Article</h3>
        <h6>Status: {{ article.get_status_display }}</h6>
        <form action="#" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label>
                {% render_field form.title type="text" class="form-control" %}
            </div>
            <div class="form-group">
                <label for=content">Content</label>
                {% render_field form.content type="text" class="form-control" cols="5" placeholder="Enter Content" %}
            </div>
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}
            {% if success %}
                <div>Success</div>
            {% endif %}
            <button class="btn btn-info">Update Record</button>
        </form>
    </div>

{% endblock %}

templates/blog/article_edited.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <div class="text-center"><h3>Articles Edited by USER: {{ request.user }}</h3></div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Title</th>
                <th>Written By</th>
                <th>created at</th>
            </tr>
            </thead>
            <tbody>
            {% if articles %}
                {% for article in articles %}
                    <tr>
                        <td scope="row"><a href="{% url "blog:article_detail" article.id %}">{{ article.title }}</a>
                        </td>
                        <td>{{ article.written_by.user.name }}</td>
                        <td>{{ article.created_at }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3" class="text-center ">No Data</td>
                </tr>
            {% endif %}

            </tbody>
        </table>
    </div>
{% endblock %}

templates/blog/article_list.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% block body %}
    <h2>USER: {{ request.user }}</h2>
    <div class=''>
        <h3>Create Article</h3>
        <form action="#" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="title">Title</label>
                {% render_field form.title type="text" class="form-control" %}
            </div>
            <div class="form-group">
                <label for=content">Content</label>
                {% render_field form.content type="text" class="form-control" cols="5" placeholder="Enter Content" %}
            </div>
            {% if form.errors %}
                {{ form.errors }}
            {% endif %}
            <button class="btn btn-info">Create New</button>
        </form>
    </div>
    <div class="text-center"><h3>Articles List</h3></div>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>Title</th>
                <th>Written By</th>
                <th>created at</th>
            </tr>
            </thead>
            <tbody>
            {% if articles %}
                {% for article in articles %}
                    <tr>
                        <td scope="row"><a href="{% url "blog:article_detail" article.id %}">{{ article.title }}</a>
                        </td>
                        <td>{{ article.written_by.user.name }}</td>
                        <td>{{ article.created_at }}</td>
                    </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3" class="text-center ">No Data</td>
                </tr>
            {% endif %}

            </tbody>
        </table>
    </div>
{% endblock %}